export const countries = [ 
    {text: 'Afghanistan', key: 'AF',value:"Afghanistan"}, 
    {text: 'Åland Islands', key: 'AX',value:"Åland Islands"}, 
    {text: 'Albania', key: 'AL',value:"Albania"}, 
    {text: 'Algeria', key: 'DZ',value:"Algeria"}, 
    {text: 'American Samoa', key: 'AS',value:"American Samoa"}, 
    {text: 'AndorrA', key: 'AD',value:"AndorrA"}, 
    {text: 'Angola', key: 'AO',value:"Angola"}, 
    {text: 'Anguilla', key: 'AI',value:"Anguilla"}, 
    {text: 'Antarctica', key: 'AQ',value:"Antarctica"}, 
    {text: 'Antigua and Barbuda', key: 'AG',value:"Antigua and Barbuda"}, 
    {text: 'Argentina', key: 'AR',value:"Argentina"}, 
    {text: 'Armenia', key: 'AM',value:"Armenia"}, 
    {text: 'Aruba', key: 'AW',value:"Aruba"}, 
    {text: 'Australia', key: 'AU',value:"Australia"}, 
    {text: 'Austria', key: 'AT',value:"Austria"}, 
    {text: 'Azerbaijan', key: 'AZ',value:"Azerbaijan"}, 
    {text: 'Bahamas', key: 'BS',value:"Bahamas"}, 
    {text: 'Bahrain', key: 'BH',value:""}, 
    {text: 'Bangladesh', key: 'BD',value:""}, 
    {text: 'Barbados', key: 'BB',value:""}, 
    {text: 'Belarus', key: 'BY',value:""}, 
    {text: 'Belgium', key: 'BE',value:""}, 
    {text: 'Belize', key: 'BZ',value:""}, 
    {text: 'Benin', key: 'BJ',value:""}, 
    {text: 'Bermuda', key: 'BM',value:""}, 
    {text: 'Bhutan', key: 'BT',value:""}, 
    {text: 'Bolivia', key: 'BO',value:""}, 
    {text: 'Bosnia and Herzegovina', key: 'BA',value:""}, 
    {text: 'Botswana', key: 'BW',value:""}, 
    {text: 'Bouvet Island', key: 'BV',value:""}, 
    {text: 'Brazil', key: 'BR',value:""}, 
    {text: 'British Indian Ocean Territory', key: 'IO',value:""}, 
    {text: 'Brunei Darussalam', key: 'BN',value:""}, 
    {text: 'Bulgaria', key: 'BG',value:""}, 
    {text: 'Burkina Faso', key: 'BF',value:""}, 
    {text: 'Burundi', key: 'BI',value:""}, 
    {text: 'Cambodia', key: 'KH',value:""}, 
    {text: 'Cameroon', key: 'CM',value:""}, 
    {text: 'Canada', key: 'CA',value:""}, 
    {text: 'Cape Verde', key: 'CV',value:""}, 
    {text: 'Cayman Islands', key: 'KY',value:""}, 
    {text: 'Central African Republic', key: 'CF',value:""}, 
    {text: 'Chad', key: 'TD',value:""}, 
    {text: 'Chile', key: 'CL',value:""}, 
    {text: 'China', key: 'CN',value:""}, 
    {text: 'Christmas Island', key: 'CX',value:""}, 
    {text: 'Cocos (Keeling) Islands', key: 'CC',value:""}, 
    {text: 'Colombia', key: 'CO',value:""}, 
    {text: 'Comoros', key: 'KM',value:""}, 
    {text: 'Congo', key: 'CG',value:""}, 
    {text: 'Congo, The Democratic Republic of the', key: 'CD',value:""}, 
    {text: 'Cook Islands', key: 'CK',value:""}, 
    {text: 'Costa Rica', key: 'CR',value:""}, 
    {text: 'Cote D\'Ivoire', key: 'CI',value:""}, 
    {text: 'Croatia', key: 'HR',value:""}, 
    {text: 'Cuba', key: 'CU',value:""}, 
    {text: 'Cyprus', key: 'CY',value:""}, 
    {text: 'Czech Republic', key: 'CZ',value:""}, 
    {text: 'Denmark', key: 'DK',value:""}, 
    {text: 'Djibouti', key: 'DJ',value:""}, 
    {text: 'Dominica', key: 'DM',value:""}, 
    {text: 'Dominican Republic', key: 'DO',value:""}, 
    {text: 'Ecuador', key: 'EC',value:""}, 
    {text: 'Egypt', key: 'EG',value:""}, 
    {text: 'El Salvador', key: 'SV',value:""}, 
    {text: 'Equatorial Guinea', key: 'GQ',value:""}, 
    {text: 'Eritrea', key: 'ER',value:""}, 
    {text: 'Estonia', key: 'EE',value:""}, 
    {text: 'Ethiopia', key: 'ET',value:""}, 
    {text: 'Falkland Islands (Malvinas)', key: 'FK',value:""}, 
    {text: 'Faroe Islands', key: 'FO',value:""}, 
    {text: 'Fiji', key: 'FJ',value:""}, 
    {text: 'Finland', key: 'FI',value:""}, 
    {text: 'France', key: 'FR',value:""}, 
    {text: 'French Guiana', key: 'GF',value:""}, 
    {text: 'French Polynesia', key: 'PF',value:""}, 
    {text: 'French Southern Territories', key: 'TF',value:""}, 
    {text: 'Gabon', key: 'GA',value:""}, 
    {text: 'Gambia', key: 'GM',value:""}, 
    {text: 'Georgia', key: 'GE',value:""}, 
    {text: 'Germany', key: 'DE',value:""}, 
    {text: 'Ghana', key: 'GH',value:""}, 
    {text: 'Gibraltar', key: 'GI',value:""}, 
    {text: 'Greece', key: 'GR',value:""}, 
    {text: 'Greenland', key: 'GL',value:""}, 
    {text: 'Grenada', key: 'GD',value:""}, 
    {text: 'Guadeloupe', key: 'GP',value:""}, 
    {text: 'Guam', key: 'GU',value:""}, 
    {text: 'Guatemala', key: 'GT',value:""}, 
    {text: 'Guernsey', key: 'GG',value:""}, 
    {text: 'Guinea', key: 'GN',value:""}, 
    {text: 'Guinea-Bissau', key: 'GW',value:""}, 
    {text: 'Guyana', key: 'GY',value:""}, 
    {text: 'Haiti', key: 'HT',value:""}, 
    {text: 'Heard Island and Mcdonald Islands', key: 'HM',value:""}, 
    {text: 'Holy See (Vatican City State)', key: 'VA',value:""}, 
    {text: 'Honduras', key: 'HN',value:""}, 
    {text: 'Hong Kong', key: 'HK',value:""}, 
    {text: 'Hungary', key: 'HU',value:""}, 
    {text: 'Iceland', key: 'IS',value:""}, 
    {text: 'India', key: 'IN',value:""}, 
    {text: 'Indonesia', key: 'ID',value:""}, 
    {text: 'Iran, Islamic Republic Of', key: 'IR',value:""}, 
    {text: 'Iraq', key: 'IQ',value:""}, 
    {text: 'Ireland', key: 'IE',value:""}, 
    {text: 'Isle of Man', key: 'IM',value:""}, 
    {text: 'Israel', key: 'IL',value:""}, 
    {text: 'Italy', key: 'IT',value:""}, 
    {text: 'Jamaica', key: 'JM',value:""}, 
    {text: 'Japan', key: 'JP',value:""}, 
    {text: 'Jersey', key: 'JE',value:""}, 
    {text: 'Jordan', key: 'JO',value:""}, 
    {text: 'Kazakhstan', key: 'KZ',value:""}, 
    {text: 'Kenya', key: 'KE',value:""}, 
    {text: 'Kiribati', key: 'KI',value:""}, 
    {text: 'Korea, Democratic People\'S Republic of', key: 'KP',value:""}, 
    {text: 'Korea, Republic of', key: 'KR',value:""}, 
    {text: 'Kuwait', key: 'KW',value:""}, 
    {text: 'Kyrgyzstan', key: 'KG',value:""}, 
    {text: 'Lao People\'S Democratic Republic', key: 'LA',value:""}, 
    {text: 'Latvia', key: 'LV',value:""}, 
    {text: 'Lebanon', key: 'LB',value:""}, 
    {text: 'Lesotho', key: 'LS',value:""}, 
    {text: 'Liberia', key: 'LR',value:""}, 
    {text: 'Libyan Arab Jamahiriya', key: 'LY',value:""}, 
    {text: 'Liechtenstein', key: 'LI',value:""}, 
    {text: 'Lithuania', key: 'LT',value:""}, 
    {text: 'Luxembourg', key: 'LU',value:""}, 
    {text: 'Macao', key: 'MO',value:""}, 
    {text: 'Macedonia, The Former Yugoslav Republic of', key: 'MK',value:""}, 
    {text: 'Madagascar', key: 'MG',value:""}, 
    {text: 'Malawi', key: 'MW',value:""}, 
    {text: 'Malaysia', key: 'MY',value:""}, 
    {text: 'Maldives', key: 'MV',value:""}, 
    {text: 'Mali', key: 'ML',value:""}, 
    {text: 'Malta', key: 'MT',value:""}, 
    {text: 'Marshall Islands', key: 'MH',value:""}, 
    {text: 'Martinique', key: 'MQ',value:""}, 
    {text: 'Mauritania', key: 'MR',value:""}, 
    {text: 'Mauritius', key: 'MU',value:""}, 
    {text: 'Mayotte', key: 'YT',value:""}, 
    {text: 'Mexico', key: 'MX',value:""}, 
    {text: 'Micronesia, Federated States of', key: 'FM',value:""}, 
    {text: 'Moldova, Republic of', key: 'MD',value:""}, 
    {text: 'Monaco', key: 'MC',value:""}, 
    {text: 'Mongolia', key: 'MN',value:""}, 
    {text: 'Montserrat', key: 'MS',value:""}, 
    {text: 'Morocco', key: 'MA',value:""}, 
    {text: 'Mozambique', key: 'MZ',value:""}, 
    {text: 'Myanmar', key: 'MM',value:""}, 
    {text: 'Namibia', key: 'NA',value:""}, 
    {text: 'Nauru', key: 'NR',value:""}, 
    {text: 'Nepal', key: 'NP',value:""}, 
    {text: 'Netherlands', key: 'NL',value:""}, 
    {text: 'Netherlands Antilles', key: 'AN',value:""}, 
    {text: 'New Caledonia', key: 'NC',value:""}, 
    {text: 'New Zealand', key: 'NZ',value:""}, 
    {text: 'Nicaragua', key: 'NI',value:""}, 
    {text: 'Niger', key: 'NE',value:""}, 
    {text: 'Nigeria', key: 'NG',value:""}, 
    {text: 'Niue', key: 'NU'}, 
    {text: 'Norfolk Island', key: 'NF'}, 
    {text: 'Northern Mariana Islands', key: 'MP'}, 
    {text: 'Norway', key: 'NO'}, 
    {text: 'Oman', key: 'OM'}, 
    {text: 'Pakistan', key: 'PK'}, 
    {text: 'Palau', key: 'PW'}, 
    {text: 'Palestinian Territory, Occupied', key: 'PS'}, 
    {text: 'Panama', key: 'PA'}, 
    {text: 'Papua New Guinea', key: 'PG'}, 
    {text: 'Paraguay', key: 'PY'}, 
    {text: 'Peru', key: 'PE'}, 
    {text: 'Philippines', key: 'PH'}, 
    {text: 'Pitcairn', key: 'PN'}, 
    {text: 'Poland', key: 'PL'}, 
    {text: 'Portugal', key: 'PT'}, 
    {text: 'Puerto Rico', key: 'PR'}, 
    {text: 'Qatar', key: 'QA'}, 
    {text: 'Reunion', key: 'RE'}, 
    {text: 'Romania', key: 'RO'}, 
    {text: 'Russian Federation', key: 'RU'}, 
    {text: 'RWANDA', key: 'RW'}, 
    {text: 'Saint Helena', key: 'SH'}, 
    {text: 'Saint Kitts and Nevis', key: 'KN'}, 
    {text: 'Saint Lucia', key: 'LC'}, 
    {text: 'Saint Pierre and Miquelon', key: 'PM'}, 
    {text: 'Saint Vincent and the Grenadines', key: 'VC'}, 
    {text: 'Samoa', key: 'WS'}, 
    {text: 'San Marino', key: 'SM'}, 
    {text: 'Sao Tome and Principe', key: 'ST'}, 
    {text: 'Saudi Arabia', key: 'SA'}, 
    {text: 'Senegal', key: 'SN'}, 
    {text: 'Serbia and Montenegro', key: 'CS'}, 
    {text: 'Seychelles', key: 'SC'}, 
    {text: 'Sierra Leone', key: 'SL'}, 
    {text: 'Singapore', key: 'SG'}, 
    {text: 'Slovakia', key: 'SK'}, 
    {text: 'Slovenia', key: 'SI'}, 
    {text: 'Solomon Islands', key: 'SB'}, 
    {text: 'Somalia', key: 'SO'}, 
    {text: 'South Africa', key: 'ZA'}, 
    {text: 'South Georgia and the South Sandwich Islands', key: 'GS'}, 
    {text: 'Spain', key: 'ES'}, 
    {text: 'Sri Lanka', key: 'LK'}, 
    {text: 'Sudan', key: 'SD'}, 
    {text: 'Suritext', key: 'SR'}, 
    {text: 'Svalbard and Jan Mayen', key: 'SJ'}, 
    {text: 'Swaziland', key: 'SZ'}, 
    {text: 'Sweden', key: 'SE'}, 
    {text: 'Switzerland', key: 'CH'}, 
    {text: 'Syrian Arab Republic', key: 'SY'}, 
    {text: 'Taiwan, Province of China', key: 'TW'}, 
    {text: 'Tajikistan', key: 'TJ'}, 
    {text: 'Tanzania, United Republic of', key: 'TZ'}, 
    {text: 'Thailand', key: 'TH'}, 
    {text: 'Timor-Leste', key: 'TL'}, 
    {text: 'Togo', key: 'TG'}, 
    {text: 'Tokelau', key: 'TK'}, 
    {text: 'Tonga', key: 'TO'}, 
    {text: 'Trinidad and Tobago', key: 'TT'}, 
    {text: 'Tunisia', key: 'TN'}, 
    {text: 'Turkey', key: 'TR'}, 
    {text: 'Turkmenistan', key: 'TM'}, 
    {text: 'Turks and Caicos Islands', key: 'TC'}, 
    {text: 'Tuvalu', key: 'TV'}, 
    {text: 'Uganda', key: 'UG'}, 
    {text: 'Ukraine', key: 'UA'}, 
    {text: 'United Arab Emirates', key: 'AE'}, 
    {text: 'United Kingdom', key: 'GB'}, 
    {text: 'United States', key: 'US'}, 
    {text: 'United States Minor Outlying Islands', key: 'UM'}, 
    {text: 'Uruguay', key: 'UY'}, 
    {text: 'Uzbekistan', key: 'UZ'}, 
    {text: 'Vanuatu', key: 'VU'}, 
    {text: 'Venezuela', key: 'VE'}, 
    {text: 'Viet Nam', key: 'VN'}, 
    {text: 'Virgin Islands, British', key: 'VG'}, 
    {text: 'Virgin Islands, U.S.', key: 'VI'}, 
    {text: 'Wallis and Futuna', key: 'WF'}, 
    {text: 'Western Sahara', key: 'EH'}, 
    {text: 'Yemen', key: 'YE'}, 
    {text: 'Zambia', key: 'ZM'}, 
    {text: 'Zimbabwe', key: 'ZW'} 
]